theme: jekyll-theme-midnight
title: Welcome to TotallyNotARobot404's capstone homepage!
description: This is a website dedicated to the collection of everything TotallyNotARobot404 has done throughout their SNHU computer science career!
